### ISSUE TITLE
[iOS] Undefined symbols

### ISSUE THREAD

**Issue by rtiagom** [kornelski/rust-security-framework#215]
Undefined symbols when using this library with an iOS project with Xcode 16. The project includes the security.framework.

```
Xcode 16.0
Build version 16A242d

Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
Undefined symbols for architecture arm64:
  "_CMSDecoderCopySignerTimestamp", referenced from:
      security_framework::cms::decoder::CMSDecoder::get_signer_timestamp::h5974aee7f87b900b in libapp.a[397](security_framework-da88d0519bb50a42.security_framework.66c9132394a49f5d-cgu.02.rcgu.o)
  "_CMSDecoderCopySignerTimestampCertificates", referenced from:
      security_framework::cms::decoder::CMSDecoder::get_signer_timestamp_certificates::hf327d2c00d247bdc in libapp.a[397](security_framework-da88d0519bb50a42.security_framework.66c9132394a49f5d-cgu.02.rcgu.o)
  "_CMSDecoderCopySignerTimestampWithPolicy", referenced from:
      security_framework::cms::decoder::CMSDecoder::get_signer_timestamp_with_policy::h56e708e547817c85 in libapp.a[397](security_framework-da88d0519bb50a42.security_framework.66c9132394a49f5d-cgu.02.rcgu.o)
  "_CMSEncoderCopySignerTimestamp", referenced from:
      security_framework::cms::encoder::CMSEncoder::get_signer_timestamp::h559e11f1beb52f77 in libapp.a[398](security_framework-da88d0519bb50a42.security_framework.66c9132394a49f5d-cgu.03.rcgu.o)
  "_CMSEncoderCopySignerTimestampWithPolicy", referenced from:
      security_framework::cms::encoder::CMSEncoder::get_signer_timestamp_with_policy::h2ac30f714dfbf753 in libapp.a[398](security_framework-da88d0519bb50a42.security_framework.66c9132394a49f5d-cgu.03.rcgu.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rtiagom** [comment]
Works with security-framework 2.11.1
